### ISSUE TITLE
How to generate file above_table_pointcloud.vtp?

### ISSUE THREAD

**Issue by hoangcuongbk80** [RobotLocomotion/LabelFusion#28]
I am trying to segment the pointcloud above the table through run_alignment_tool, but I don't see any file like   above_table_pointcloud.vtp genneted:

![labelfusion](https://user-images.githubusercontent.com/10355081/42279435-0e021096-7f9e-11e8-8b4c-ef452c4c4867.png)

Any help would be appreciated!

**Comment by 5yler** [comment]
It's been a while since I've used LabelFusion but here are my notes:

- run_alignment_tool => registration
- shift+click a point on table, shift+click a point above table
F8 (Director terminal): 
- `gr.rotateAndSegmentPointcloud()`
- `gr.launchObjectAlignment('drill')`

(This was over a year ago so the process may have changed)

From your screenshot above it appears that maybe the `gr.segmentTable()` command did not get executed correctly (note that it is green in the directorPython window, as opposed to the `gr.saveAboveTablePolyData()` which is in black. Perhaps try again and first press enter in the directorPython window until you get a `>>>` at the start of your prompt?

**Comment by hoangcuongbk80** [comment]
Many thanks for your help! I will check it.

**Comment by hoangcuongbk80** [comment]
Resolved: Commands on directorPython window should be typed instead of copy and paste.
